language: csharp
sudo: required
mono: none
dotnet: 2.0.0
dist: trusty
branches:
  only:
  - master
install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update
  - sudo apt-get install -y powershell
script:
  - pushd PolarisCore
  - dotnet restore
  - dotnet build -f netstandard2.0
  - popd && pushd test
  - pwsh -c 'Install-Module Pester; Invoke-Pester -ExcludeTag VersionChecks -EnableExit'
  - popd
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9b9664c60325fbb70dd7
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
